version: '3'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finnconnect
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL:-"jdbc:postgresql://postgres:5432/finnconnect_ktor"}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
networks:
  default:
    driver: bridge