name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Deploy to Server
        env:
          OPEN_EXCHANGE_API_KEY: ${{ secrets.OPEN_EXCHANGE_API_KEY }}
          PG_PASSWD: ${{ secrets.PG_PASSWD }}
          PG_URL: ${{ secrets.PG_URL }}
          PG_USERNAME: ${{ secrets.PG_USERNAME }}
          #MONZO_CLIENT_ID: ${{ secrets.MONZO_CLIENT_ID }}
          #MONZO_CLIENT_SECRET: ${{ secrets.MONZO_CLIENT_SECRET }}
        run: |
          echo "Deploying to server..."
          # Add your deployment script here, making use of the secrets
